### PR TITLE
Add panr support to 4.4.1

### PR DESCRIPTION
**Pull request by adaviding**
## Links
* https://github.com/Panopto/panopto-core/pull/24587
* https://github.com/Panopto/build-ffmpeg/pull/2

## Description
* Add panr support to 4.4.1
  * git cherry-pick becf711ec40918954c0b9b73895782a7c09a3832
* Fix memory consumption error in fps filter (https://trac.ffmpeg.org/ticket/9081)
  * git cherry-pick 531d09fb2d6bddb968dbef1fbb8b351aed85cbfa
  * git cherry-pick 01440e258827f77990d918bfeb77cb613bc3733a

The memory consumption fixes were taken from master (pre-5.1.0).

### CODE REVIEW

**Review by derek-se — APPROVED** [review]
Looks like this includes the esds fix and doesn't port setts (intentionally as that should be in 4.4 already). Go for it

**Comment by adaviding** [comment]
Cherry-picked an important fix from upstream master.  https://github.com/FFmpeg/FFmpeg/commit/01440e258827f77990d918bfeb77cb613bc3733a

**Comment by adaviding** [comment]
I am removing the commit from our branch because it doesn't fix the bug when based off of 4.4.1.

https://github.com/FFmpeg/FFmpeg/commit/01440e258827f77990d918bfeb77cb613bc3733a

For more information:  https://trac.ffmpeg.org/ticket/9081#comment:12

**Comment by adaviding** [comment]
Fixed memory consumption error in fps filter (https://trac.ffmpeg.org/ticket/9081)
* git cherry-pick 531d09fb2d6bddb968dbef1fbb8b351aed85cbfa
* git cherry-pick 01440e258827f77990d918bfeb77cb613bc3733a

**Pull request merged**
